version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-brian"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w8zc7gxx87rc"
s3_prefix = "sam-app-brian"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

